### ISSUE TITLE
Letsencrypt cert doesn't automatically update

### ISSUE THREAD

**Issue by mjbruder** [fatk/docker-letsencrypt-nginx-proxy-companion-examples#16]
I noticed that my Letsencrypt cert isn't automatically renewing. Is there a cron job or something that needs to run to check the expiration and pull down an updated cert? The initial cert worked just fine.

**Comment by mjbruder** [comment]
This was related to [https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/issues/130](url)

**Comment by jazari-akuna** [comment]
This is a 404

**Comment by mjbruder** [comment]
Odd. That is the correct link. It should be https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/issues/130

If I copy/paste the URL into a browser it works fine.
