### ISSUE TITLE
project docker-flow-proxy

### ISSUE THREAD

**Issue by pascalandy** [fatk/docker-letsencrypt-nginx-proxy-companion-examples#2]
Hey Karl,
There is also this project that looks promising!

http://technologyconversations.com/2016/03/21/docker-flow-proxy-on-demand-haproxy-service-discovery-and-reconfiguration/
https://github.com/vfarcic/docker-flow-proxy

**Comment by fatk** [comment]
It does! I'll look into it, even though i don't really know much about haproxy, i've been willing to benchmark it against nginx, but i think i'll try it after the ubuntu LTS update, so that i can use overlayfs instead of aufs.

 :+1:  Thanks!
