### ISSUE TITLE
Error with nginx-gen: "unable to parse template: read /etc/docker-gen/templates/nginx.tmpl: is a directory"

### ISSUE THREAD

**Issue by stephan-nordnes-eriksen** [fatk/docker-letsencrypt-nginx-proxy-companion-examples#5]
When trying to start `nginx-gen`, this error appears in the docker logs:

```
2016/04/23 16:15:05 unable to parse template: read /etc/docker-gen/templates/nginx.tmpl: is a directory
```

This results in the template not compiling properly and the container not booting. I am getting this error with both normal docker and docker-compose.

I am using osx 10.11.5 Beta, `Docker version 1.11.0, build 4dc5990` and ´docker-compose version 1.7.0, build 0d7bf73`against a docker server on digitalocean running`ubuntu 15.10 x64`and`docker v1.11.0`(booted with`docker-machine create --driver digitalocean ...`).

I have found that this issue might be related to one or more of these other issues:

https://github.com/docker/docker/issues/19304
https://github.com/docker/compose/issues/424
https://github.com/jwilder/nginx-proxy/issues/390

I have not been able to successfully run/start nginx-gen against my droplet, but I am able to run this successfully against my local virtualbox machine.

I have tried using absolute paths, I have tried moving the file to the same directory as the docker-compose yml, all with no luck :(

**Comment by stephan-nordnes-eriksen** [comment]
In case anyone else is getting this issue; my solution was to move the nginx-gen into a dockerfile, and use `COPY` to add the template.

Dockerfile (i put it in the root directory, but you could probably organise it into a folder):

```
FROM jwilder/docker-gen

# VOLUME ["/var/run/docker.sock:/var/run/docker.sock"]
# COPY /var/run/docker.sock /tmp/docker.sock
COPY ./volumes/proxy/templates/nginx.tmpl /etc/docker-gen/templates/nginx.tmpl


ENTRYPOINT ["/usr/local/bin/docker-gen", "-notify-sighup", "nginx", "-watch", "-only-exposed", "-wait", "5s:30s", "/etc/docker-gen/templates/nginx.tmpl", "/etc/nginx/conf.d/default.conf"]

```

Docker compose entry:

```
nginx-gen:
  build: ../../../
  container_name: nginx-gen
  volumes:
    - "/var/run/docker.sock:/tmp/docker.sock:ro"
  volumes_from:
    - nginx
```

**Comment by mathuin** [comment]
My solution to this was to change the template line to refer to the directory containing the template instead of the file:

`- "./volumes/proxy/templates:/etc/docker-gen/templates:ro"`

Hope that helps!

**Comment by fatk** [comment]
I've run into this exact same issue, however, i managed to track it back to mount issue with Docker VM on Mac OS (in my case), that got troubleshooted through an ssh into the machine and fixed with a reboot.

I'm still using the setup as-is and the issue hasn't come back yet.

Could you try with the old setup and see if the problem still exists?

Thanks.

**Comment by replaid** [comment]
I just hit this. Traced it to a silly forehead-slapper: was running `docker-machine` against a remote machine, so the file wasn't available on the machine I was launching from. And apparently Docker mounts a directory when there's not a file present matching the file named in the host part of a `-v /host/file:/container/file` argument.

Thought I'd document that goof for posterity, since it will present this way.

**Comment by Banashek** [comment]
The docker file solution mentioned by @stephan-nordnes-eriksen worked for me.

**Comment by murbanowicz** [comment]
any good solution for this ? 

@stephan-nordnes-eriksen I've created Dockerfile in the same folder as my docker-compose.
it fails to build:
Step 2/3 : COPY ./volumes/proxy/templates/nginx.tmpl /etc/docker-gen/templates/nginx.tmpl
ERROR: Service 'nginx-gen' failed to build: lstat volumes/proxy/templates/nginx.tmpl: no such file or directory

**Comment by jimdelois** [comment]
@mathuin 's solution worked for me...

**Comment by hoodsy** [comment]
@replaid Hitting the same issue you mentioned...

How did you end up going about this? I'd love to deploy entirely from my local machine (via `docker-machine`) without ssh'ing into the remote machine and running a `git clone` or something.

**Comment by replaid** [comment]
@hoodsy I believe the options for that situation are either to ensure the file exists or mount a whole directory.
