### ISSUE TITLE
Wrong order when compose up crash nginx.

### ISSUE THREAD

**Issue by hetii** [fatk/docker-letsencrypt-nginx-proxy-companion-examples#7]
Hello ;)

Sometimes nginx is executed first and then have no configuration from nginx-gen.
Also its not possible to use "depends_on" directive cause it have volumes_from and then we have:

ERROR: Circular dependency between nginx and nginx-gen

`Starting simple-site
Starting nginx
Starting nginx-gen
Starting letsencrypt-nginx-proxy-companion
Attaching to simple-site, nginx, nginx-gen, letsencrypt-nginx-proxy-companion
nginx                             | 2016/07/20 14:19:34 [emerg] 1#1: open() "/etc/nginx/vhost.d/default" failed (2: No such file or directory) in /etc/nginx/conf.d/default.conf:56
nginx                             | nginx: [emerg] open() "/etc/nginx/vhost.d/default" failed (2: No such file or directory) in /etc/nginx/conf.d/default.conf:56
nginx-gen                         | 2016/07/20 14:19:34 Generated '/etc/nginx/conf.d/default.conf' from 2 containers
nginx-gen                         | 2016/07/20 14:19:34 Sending container 'nginx' signal '1'
nginx-gen                         | 2016/07/20 14:19:34 Error sending signal to container: API error (500): Cannot kill container nginx: Container 2c79e66156352b697fd5020efd2147484783f234a477da238741bea3477ef117 is not running
nginx-gen                         | 2016/07/20 14:19:34 Watching docker events
nginx exited with code 1
nginx-gen                         | 2016/07/20 14:19:34 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification ''
nginx-gen                         | 2016/07/20 14:19:34 Received event start for container 147eda37160f
letsencrypt-nginx-proxy-companion | 2016/07/20 14:19:34 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/update_certs'
letsencrypt-nginx-proxy-companion | 2016/07/20 14:19:34 Watching docker events
letsencrypt-nginx-proxy-companion | 2016/07/20 14:19:34 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/update_certs'
letsencrypt-nginx-proxy-companion | Reloading nginx proxy (using separate container nginx-gen)...
nginx-gen                         | 2016/07/20 14:19:35 Received signal: hangup
nginx-gen                         | 2016/07/20 14:19:35 Received signal: hangup
letsencrypt-nginx-proxy-companion | Creating/renewal mysite.com certificates... (mysite.com)
nginx-gen                         | 2016/07/20 14:19:35 Generated '/etc/nginx/conf.d/default.conf' from 2 containers
nginx-gen                         | 2016/07/20 14:19:35 Sending container 'nginx' signal '1'
nginx-gen                         | 2016/07/20 14:19:35 Error sending signal to container: API error (500): Cannot kill container nginx: Container 2c79e66156352b697fd5020efd2147484783f234a477da238741bea3477ef117 is not running
letsencrypt-nginx-proxy-companion | 2016-07-20 14:19:35,291:INFO:simp_le:1383: Certificates already exist and renewal is not necessary, exiting with status code 1.
letsencrypt-nginx-proxy-companion | Sleep for 3600s
nginx-gen                         | 2016/07/20 14:19:39 Debounce minTimer fired
nginx-gen                         | 2016/07/20 14:19:39 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification ''`

**Comment by fatk** [comment]
I believe this got fixed by docker-gen.
